name: Publish latest

on:
  push:
    branches: [master, main]

env:
  IMAGE_NAME: "hstreamdb/hstream"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Push image to dockerhub
        run: |
          echo "Login dockerhub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "Build & Push ${IMAGE_NAME}..."
          docker build . -t ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
